---
# tasks file for roles/nginx

- name: install nginx
  yum:
    name: "nginx"
    update_cache: yes
    state: present

- name: Start nginx service
  service: name=nginx enabled=yes state=started

- name: copy nginx conf file
  template:
    src: 'nginx.conf.j2'
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart nginx service

- name: create sites-available and sites-enabled directories for vhosts
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - 'sites-available'
    - 'sites-enabled'
