---
# tasks file for roles/nodejs

- name: installing nodejs packages
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items: "{{ node_packages }}"

- name: installing pm2 and socket.io
  npm:
    name: '{{ item }}'
    global: yes
  with_items:
    - 'pm2'
    - 'socket.io'

- name: creating pm2 system service
  command: 'pm2 startup'